# save as .github/workflows/MacOS.yml
name: MacOS

on:
  push:
    branches:
          - main
          - master
          - 'releases/**'
  pull_request:
  schedule: # MIN HOUR DAYOFMONTH MONTH DAYOFWEEK - schedule a monthly run - just keeping an eye on long-time-not-touched repositories
    - cron: '34 0 4 * *'

jobs:
  launch:
    uses: ./.github/workflows/runner.yml
    with:
      os: ${{ github.workflow }}
      os_version: latest
      raku_version: latest
      verbosity: error
      test_degree: 2
      skip_deps_tests: false
      run_prove6: ${{ github.event_name == 'pull_request' }}
      install_module: ${{ github.event_name != 'pull_request' }}
      run_tests_script: ${{ github.event_name == 'pull_request' }}
