# save as .github/workflows/runner.yml
name: runner

on:
  workflow_call:
    inputs:
      os:
        description: Operating System to run on
        required: true
        type: string
      os_version:
        description: OS version
        required: true
        type: string
      raku_version:
        description: Raku version latest or 2023.10, etc.
        required: true
        type: string
      verbosity:
        description: verbosity
        required: true
        type: string
      test_degree:
        description: install module
        required: true
        type: string
      skip_deps_tests:
        description: skip dependency tests
        required: true
        type: boolean
      run_prove6:
        description: run prove6
        required: true
        type: boolean
      run_tests_script:
        description: run-tests.raku
        required: true
        type: boolean
      install_module:
        description: install module
        required: true
        type: boolean
      ad_hoc_command:
        description: ad-hoc command
        required: false
        type: string

jobs:
  runner:
    runs-on: ${{ inputs.os }}-${{ inputs.os_version }}
    steps:

    - uses: Raku/setup-raku@v1
      with:
        raku-version: ${{ inputs.raku_version }}

    - uses: actions/checkout@v4

    - name: Install Dependencies
      if: ${{ ! inputs.skip_deps_tests }}
      run: zef --${{ inputs.verbosity }} --deps-only --fetch-degree=4 --test-degree=${{ inputs.test_degree }} install .

    - name: Install Dependencies quick and dirty - skip tests
      if: ${{ inputs.skip_deps_tests }}
      run: zef --${{ inputs.verbosity }} --deps-only --/test --fetch-degree=4 install .

    - name: Run run-tests.raku
      if: ${{ inputs.run_tests_script }}
      run: raku -- run-tests.raku --author=True

    - name: Run prove6
      if: ${{ inputs.run_prove6 }}
      run: |
        zef install --/test --fetch-degree=4 --test-degree=${{ inputs.test_degree }} App::Prove6
        prove6 --version
        prove6 --jobs ${{ inputs.test_degree }} --lib --timer --verbose

    - name: Install Module
      if: ${{ inputs.install_module }}
      run: zef --${{ inputs.verbosity }} --/depends --fetch-degree=4 --test-degree=${{ inputs.test_degree }} install .

    - name: Ad-hoc command
      if: ${{ inputs.ad_hoc_command }}
      run: ${{ inputs.ad_hoc_command }}